dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  rinkeby:
    verify: True
